/*
Copyright 2024 The TTL Reaper Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by informer-gen. DO NOT EDIT.

package v1alpha1

import (
	context "context"
	time "time"

	apisttlreaperv1alpha1 "github.com/infernus01/ttl-reaper/pkg/apis/ttlreaper/v1alpha1"
	versioned "github.com/infernus01/ttl-reaper/pkg/client/clientset/versioned"
	internalinterfaces "github.com/infernus01/ttl-reaper/pkg/client/informers/externalversions/internalinterfaces"
	ttlreaperv1alpha1 "github.com/infernus01/ttl-reaper/pkg/client/listers/ttlreaper/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
	watch "k8s.io/apimachinery/pkg/watch"
	cache "k8s.io/client-go/tools/cache"
)

// TTLReaperConfigInformer provides access to a shared informer and lister for
// TTLReaperConfigs.
type TTLReaperConfigInformer interface {
	Informer() cache.SharedIndexInformer
	Lister() ttlreaperv1alpha1.TTLReaperConfigLister
}

type tTLReaperConfigInformer struct {
	factory          internalinterfaces.SharedInformerFactory
	tweakListOptions internalinterfaces.TweakListOptionsFunc
	namespace        string
}

// NewTTLReaperConfigInformer constructs a new informer for TTLReaperConfig type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewTTLReaperConfigInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers) cache.SharedIndexInformer {
	return NewFilteredTTLReaperConfigInformer(client, namespace, resyncPeriod, indexers, nil)
}

// NewFilteredTTLReaperConfigInformer constructs a new informer for TTLReaperConfig type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewFilteredTTLReaperConfigInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers, tweakListOptions internalinterfaces.TweakListOptionsFunc) cache.SharedIndexInformer {
	return cache.NewSharedIndexInformer(
		&cache.ListWatch{
			ListFunc: func(options v1.ListOptions) (runtime.Object, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.TtlreaperV1alpha1().TTLReaperConfigs(namespace).List(context.TODO(), options)
			},
			WatchFunc: func(options v1.ListOptions) (watch.Interface, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.TtlreaperV1alpha1().TTLReaperConfigs(namespace).Watch(context.TODO(), options)
			},
		},
		&apisttlreaperv1alpha1.TTLReaperConfig{},
		resyncPeriod,
		indexers,
	)
}

func (f *tTLReaperConfigInformer) defaultInformer(client versioned.Interface, resyncPeriod time.Duration) cache.SharedIndexInformer {
	return NewFilteredTTLReaperConfigInformer(client, f.namespace, resyncPeriod, cache.Indexers{cache.NamespaceIndex: cache.MetaNamespaceIndexFunc}, f.tweakListOptions)
}

func (f *tTLReaperConfigInformer) Informer() cache.SharedIndexInformer {
	return f.factory.InformerFor(&apisttlreaperv1alpha1.TTLReaperConfig{}, f.defaultInformer)
}

func (f *tTLReaperConfigInformer) Lister() ttlreaperv1alpha1.TTLReaperConfigLister {
	return ttlreaperv1alpha1.NewTTLReaperConfigLister(f.Informer().GetIndexer())
}
