/*
Copyright 2024 The TTL Reaper Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	v1alpha1 "github.com/infernus01/ttl-reaper/pkg/apis/ttlreaper/v1alpha1"
	ttlreaperv1alpha1 "github.com/infernus01/ttl-reaper/pkg/client/clientset/versioned/typed/ttlreaper/v1alpha1"
	gentype "k8s.io/client-go/gentype"
)

// fakeTTLReaperConfigs implements TTLReaperConfigInterface
type fakeTTLReaperConfigs struct {
	*gentype.FakeClientWithList[*v1alpha1.TTLReaperConfig, *v1alpha1.TTLReaperConfigList]
	Fake *FakeTtlreaperV1alpha1
}

func newFakeTTLReaperConfigs(fake *FakeTtlreaperV1alpha1, namespace string) ttlreaperv1alpha1.TTLReaperConfigInterface {
	return &fakeTTLReaperConfigs{
		gentype.NewFakeClientWithList[*v1alpha1.TTLReaperConfig, *v1alpha1.TTLReaperConfigList](
			fake.Fake,
			namespace,
			v1alpha1.SchemeGroupVersion.WithResource("ttlreaperconfigs"),
			v1alpha1.SchemeGroupVersion.WithKind("TTLReaperConfig"),
			func() *v1alpha1.TTLReaperConfig { return &v1alpha1.TTLReaperConfig{} },
			func() *v1alpha1.TTLReaperConfigList { return &v1alpha1.TTLReaperConfigList{} },
			func(dst, src *v1alpha1.TTLReaperConfigList) { dst.ListMeta = src.ListMeta },
			func(list *v1alpha1.TTLReaperConfigList) []*v1alpha1.TTLReaperConfig {
				return gentype.ToPointerSlice(list.Items)
			},
			func(list *v1alpha1.TTLReaperConfigList, items []*v1alpha1.TTLReaperConfig) {
				list.Items = gentype.FromPointerSlice(items)
			},
		),
		fake,
	}
}
