# Example TTLReaperConfig for cleaning up Tekton PipelineRuns
apiVersion: ttlreaper.io/v1alpha1
kind: TTLReaperConfig
metadata:
  name: tekton-pipelinerun-cleanup
  namespace: tekton-pipelines
spec:
  # Target Tekton PipelineRuns in the tekton-pipelines namespace
  targetNamespace: tekton-pipelines
  targetKind: PipelineRun
  targetApiVersion: tekton.dev/v1beta1

  # Use the standard TTL field path
  ttlFieldPath: "spec.ttlSecondsAfterFinished"

  # Check every 5 minutes (300 seconds)
  checkInterval: 300

---
# Example TTLReaperConfig for cleaning up TaskRuns
apiVersion: ttlreaper.io/v1alpha1
kind: TTLReaperConfig
metadata:
  name: tekton-taskrun-cleanup
  namespace: tekton-pipelines
spec:
  targetNamespace: tekton-pipelines
  targetKind: TaskRun
  targetApiVersion: tekton.dev/v1beta1
  ttlFieldPath: "spec.ttlSecondsAfterFinished"
  checkInterval: 300

---
# Example PipelineRun with TTL configured (for testing)
apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  name: example-pipeline-run
  namespace: tekton-pipelines
spec:
  # Set TTL to 1 hour (3600 seconds) after completion
  ttlSecondsAfterFinished: 3600

  pipelineSpec:
    tasks:
      - name: hello-world
        taskSpec:
          steps:
            - name: echo
              image: alpine:latest
              command:
                - echo
              args:
                - "Hello World!"
