apiVersion: v1
kind: Namespace
metadata:
  name: ttl-reaper-system
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ttl-reaper-controller
  namespace: ttl-reaper-system
  labels:
    app: ttl-reaper-controller
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ttl-reaper-controller
  template:
    metadata:
      labels:
        app: ttl-reaper-controller
    spec:
      serviceAccountName: ttl-reaper-controller
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        fsGroup: 2000
      containers:
      - name: manager
        image: ko://github.com/shubbhar/ttl-reaper/cmd/manager
        imagePullPolicy: IfNotPresent
        command:
        - /manager
        args:
        - --leader-elect=true
        - --metrics-bind-address=:8080
        - --health-probe-bind-address=:8081
        ports:
        - containerPort: 8080
          name: metrics
          protocol: TCP
        - containerPort: 8081
          name: health
          protocol: TCP
        resources:
          limits:
            cpu: 500m
            memory: 128Mi
          requests:
            cpu: 10m
            memory: 64Mi
        livenessProbe:
          httpGet:
            path: /healthz
            port: 8081
          initialDelaySeconds: 15
          periodSeconds: 20
        readinessProbe:
          httpGet:
            path: /readyz
            port: 8081
          initialDelaySeconds: 5
          periodSeconds: 10
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - ALL
          runAsNonRoot: true
          readOnlyRootFilesystem: true
      terminationGracePeriodSeconds: 10
