/*
Copyright 2024 The TTL Reaper Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	context "context"

	ttlreaperv1alpha1 "github.com/shubbhar/ttl-reaper/pkg/apis/ttlreaper/v1alpha1"
	scheme "github.com/shubbhar/ttl-reaper/pkg/client/clientset/versioned/scheme"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	gentype "k8s.io/client-go/gentype"
)

// TTLReaperConfigsGetter has a method to return a TTLReaperConfigInterface.
// A group's client should implement this interface.
type TTLReaperConfigsGetter interface {
	TTLReaperConfigs(namespace string) TTLReaperConfigInterface
}

// TTLReaperConfigInterface has methods to work with TTLReaperConfig resources.
type TTLReaperConfigInterface interface {
	Create(ctx context.Context, tTLReaperConfig *ttlreaperv1alpha1.TTLReaperConfig, opts v1.CreateOptions) (*ttlreaperv1alpha1.TTLReaperConfig, error)
	Update(ctx context.Context, tTLReaperConfig *ttlreaperv1alpha1.TTLReaperConfig, opts v1.UpdateOptions) (*ttlreaperv1alpha1.TTLReaperConfig, error)
	// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
	UpdateStatus(ctx context.Context, tTLReaperConfig *ttlreaperv1alpha1.TTLReaperConfig, opts v1.UpdateOptions) (*ttlreaperv1alpha1.TTLReaperConfig, error)
	Delete(ctx context.Context, name string, opts v1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error
	Get(ctx context.Context, name string, opts v1.GetOptions) (*ttlreaperv1alpha1.TTLReaperConfig, error)
	List(ctx context.Context, opts v1.ListOptions) (*ttlreaperv1alpha1.TTLReaperConfigList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *ttlreaperv1alpha1.TTLReaperConfig, err error)
	TTLReaperConfigExpansion
}

// tTLReaperConfigs implements TTLReaperConfigInterface
type tTLReaperConfigs struct {
	*gentype.ClientWithList[*ttlreaperv1alpha1.TTLReaperConfig, *ttlreaperv1alpha1.TTLReaperConfigList]
}

// newTTLReaperConfigs returns a TTLReaperConfigs
func newTTLReaperConfigs(c *TtlreaperV1alpha1Client, namespace string) *tTLReaperConfigs {
	return &tTLReaperConfigs{
		gentype.NewClientWithList[*ttlreaperv1alpha1.TTLReaperConfig, *ttlreaperv1alpha1.TTLReaperConfigList](
			"ttlreaperconfigs",
			c.RESTClient(),
			scheme.ParameterCodec,
			namespace,
			func() *ttlreaperv1alpha1.TTLReaperConfig { return &ttlreaperv1alpha1.TTLReaperConfig{} },
			func() *ttlreaperv1alpha1.TTLReaperConfigList { return &ttlreaperv1alpha1.TTLReaperConfigList{} },
		),
	}
}
